# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]

jobs:

   # ✅ Run Unit Tests
  unit-test-job:
    runs-on: ubuntu-latest
    steps:

      - name: Clone Source Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test
  
  build-and-push-job:
    needs: unit-test-job
    runs-on: ubuntu-latest
    steps:

      - name: Clone Source Code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t lebondeveloppeur/backend-api-image:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: docker push lebondeveloppeur/backend-api-image:latest

  deploy-job:
    needs: build-and-push-job
    runs-on: ubuntu-latest
    steps:

      - name: Connect to the VPS using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |

            # Pull the latest Docker image
            sudo docker pull lebondeveloppeur/backend-api-image:latest

            ls -l

            sudo docker images
        